Repository lucimobility/luci-sdk-staging, pull requests merged in 2023-08, with the labels that each got.

#3 Feature/package release support
  CMakeLists.txt
  Dockerfile
  deployment-scripts/README.md
  development/Dockerfile
  development/README.md
  docs/3_Examples/slam.md
  package.xml
Labels: bug, documentation, enhancement

#4 Added action and bash script
  .github/workflows/deploy-docker.yml
  build-and-deploy-dockers.sh
Labels: enhancement

#5 Added gpg signing support
  .github/workflows/deploy-docker.yml
  build-and-deploy-dockers.sh
  development/Dockerfile
Labels: bug, enhancement

#6 Updated release script
  .github/workflows/next-docs.yml
  .github/workflows/release-docs.yml
  deployment-scripts/deploy.sh
Labels: bug

#7 Update versions and docs for new release
  .github/workflows/next-docs.yml
  .github/workflows/release-docs.yml
  README.md
  build-and-deploy-dockers.sh
  deployment-scripts/README.md
  development/README.md
  docs/1_Getting-Started/1_getting-started.md
  docs/1_Getting-Started/2_docker.md
  docs/1_Landing.md
  docs/2_Installation/0_dependencies.md
  docs/2_Installation/1_ros-install.md
  docs/2_Installation/2_install-protobuf.md
  docs/2_Installation/3_install-grpc.md
  docs/2_Installation/4_luci-ros2-sdk-install.md
  docs/3_Examples/examples.md
  release/Dockerfile
  release/README.md
  system-setup.sh
  versions.json
Labels: documentation, enhancement

#8 Update release instructions
  README.md
  docs/2_Installation/1_ros-install.md
Labels: documentation

#9 Fixed typo
  release/Dockerfile
Labels: bug

#10 update third party version
  docs/2_Installation/4_luci-ros2-sdk-install.md
  versions.json
Labels: enhancement
